<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite8d92bee2dbdffb50e5ccd96f4d988f0
{
    public static $prefixLengthsPsr4 = array (
        'H' => 
        array (
            'HiDeasWebsiteDialer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'HiDeasWebsiteDialer\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite8d92bee2dbdffb50e5ccd96f4d988f0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite8d92bee2dbdffb50e5ccd96f4d988f0::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite8d92bee2dbdffb50e5ccd96f4d988f0::$classMap;

        }, null, ClassLoader::class);
    }
}
